### ISSUE TITLE
BUG: circular recursive copy of files when using Dependency object with local_code from within local_code

### ISSUE THREAD

**Issue by jeandut** [Substra/substrafl#113]
### What are you trying to do?

I run a script inside my package that I want to list as a dependency, while copying my package it creates a temp directory holding the copy, and then it tries to copy that folder as well, which already contains the package and so forth until disk space runs out.

### Issue Description (what is happening?)

Pretty much self explanatory

### Expected Behavior (what should happen?)

It should copy only relevant files

### Operating system

MacOS

### Python version

3.9.16

### Installed Substra versions

```python
0.35.Orc1
```

**Comment by jeandut** [comment]
@ThibaultFy wasn't it solved by one of the latest releases ?

**Comment by SdgJlbl** [comment]
Indeed, well spotted 👍 
Fixed by https://github.com/Substra/substrafl/pull/118 and released in [0.37.0](https://github.com/Substra/substrafl/releases/tag/0.37.0)
